stages:
  - build
  - test

minizinc:
  stage: build
  script:
     - mkdir build
     - cd build
     - cmake -GXcode ..
     - cmake --build . --config Debug
     - cp Debug/mzn2fzn Debug/solns2out ../
  only:
     - develop
  tags:
     - mac

test_mzn:
  stage: test
  script:
     - cd tests
     - bash run-all.sh
