stages:
  - build

minizinc:
  stage: build
  script:
     - mkdir build
     - cd build
     - cmake -GXcode ..
     - cmake --build . --config Debug
     - cp Debug/mzn2fzn Debug/solns2out ../
     - cd ../tests
     - bash run-all.sh
  only:
     - develop
  tags:
     - mac
