stages:
  - build

build:osx:
  stage: build
  script:
     - mkdir build
     - cd build
     - cmake -GXcode ..
     - cmake --build . --config Debug
     - cp Debug/mzn2fzn Debug/mzn-fzn Debug/solns2out ../
  artifacts:
     path:
       - mzn2fzn
       - mzn-fzn
       - solns2out
     expire-in: 2h
  only:
     - develop
  tags:
     - mac

test:osx:
  stage: test
  script:
     - cd tests
     - bash run-all.sh
  dependencies:
     - build:osx
  only:
     - develop
  tags:
     - mac
